# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/proto/worker/v1/worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'api/proto/worker/v1/worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n api/proto/worker/v1/worker.proto\x12\tworker.v1\"\xd1\x02\n\x0cTrainRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x61taset_url\x18\x02 \x01(\t\x12&\n\ttask_type\x18\x03 \x01(\x0e\x32\x13.worker.v1.TaskType\x12\x14\n\x0cn_estimators\x18\x04 \x01(\x05\x12\x15\n\rtarget_column\x18\x06 \x01(\t\x12\x13\n\x0brandom_seed\x18\x07 \x01(\x05\x12\x14\n\x0cworker_index\x18\x08 \x01(\x05\x12\x15\n\rtotal_workers\x18\t \x01(\x05\x12\x45\n\x0fhyperparameters\x18\n \x03(\x0b\x32,.worker.v1.TrainRequest.HyperparametersEntry\x1a\x36\n\x14HyperparametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01J\x04\x08\x05\x10\x06\"1\n\rTrainResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"a\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x10\n\x08\x66\x65\x61tures\x18\x02 \x03(\x02\x12\x14\n\x0cworker_index\x18\x03 \x01(\x05\x12\x15\n\rtotal_workers\x18\x04 \x01(\x05\"&\n\x0fPredictResponse\x12\x13\n\x0bpredictions\x18\x01 \x03(\t\"\x0f\n\rHealthRequest\"!\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08*N\n\x08TaskType\x12\x14\n\x10UNSPECIFIED_TASK\x10\x00\x12\x17\n\x13\x43LASSIFICATION_TASK\x10\x01\x12\x13\n\x0fREGRESSION_TASK\x10\x02\x32\xc5\x01\n\x06Worker\x12:\n\x05Train\x12\x17.worker.v1.TrainRequest\x1a\x18.worker.v1.TrainResponse\x12@\n\x07Predict\x12\x19.worker.v1.PredictRequest\x1a\x1a.worker.v1.PredictResponse\x12=\n\x06Health\x12\x18.worker.v1.HealthRequest\x1a\x19.worker.v1.HealthResponseBLZJgithub.com/bytelisa/distributed-random-forest/api/proto/worker/v1;workerv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.proto.worker.v1.worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/bytelisa/distributed-random-forest/api/proto/worker/v1;workerv1'
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TASKTYPE']._serialized_start=629
  _globals['_TASKTYPE']._serialized_end=707
  _globals['_TRAINREQUEST']._serialized_start=48
  _globals['_TRAINREQUEST']._serialized_end=385
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_start=325
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_end=379
  _globals['_TRAINRESPONSE']._serialized_start=387
  _globals['_TRAINRESPONSE']._serialized_end=436
  _globals['_PREDICTREQUEST']._serialized_start=438
  _globals['_PREDICTREQUEST']._serialized_end=535
  _globals['_PREDICTRESPONSE']._serialized_start=537
  _globals['_PREDICTRESPONSE']._serialized_end=575
  _globals['_HEALTHREQUEST']._serialized_start=577
  _globals['_HEALTHREQUEST']._serialized_end=592
  _globals['_HEALTHRESPONSE']._serialized_start=594
  _globals['_HEALTHRESPONSE']._serialized_end=627
  _globals['_WORKER']._serialized_start=710
  _globals['_WORKER']._serialized_end=907
# @@protoc_insertion_point(module_scope)
