// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/worker/v1/worker.proto

package workerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType int32

const (
	TaskType_UNSPECIFIED_TASK    TaskType = 0
	TaskType_CLASSIFICATION_TASK TaskType = 1
	TaskType_REGRESSION_TASK     TaskType = 2
)

// Enum value maps for TaskType.
var (
	TaskType_name = map[int32]string{
		0: "UNSPECIFIED_TASK",
		1: "CLASSIFICATION_TASK",
		2: "REGRESSION_TASK",
	}
	TaskType_value = map[string]int32{
		"UNSPECIFIED_TASK":    0,
		"CLASSIFICATION_TASK": 1,
		"REGRESSION_TASK":     2,
	}
)

func (x TaskType) Enum() *TaskType {
	p := new(TaskType)
	*p = x
	return p
}

func (x TaskType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TaskType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_worker_v1_worker_proto_enumTypes[0].Descriptor()
}

func (TaskType) Type() protoreflect.EnumType {
	return &file_api_proto_worker_v1_worker_proto_enumTypes[0]
}

func (x TaskType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TaskType.Descriptor instead.
func (TaskType) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

type TrainRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	ModelId string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	// this url will redirect each worker to a specific partition of the dataset
	DatasetUrl string   `protobuf:"bytes,2,opt,name=dataset_url,json=datasetUrl,proto3" json:"dataset_url,omitempty"`
	TaskType   TaskType `protobuf:"varint,3,opt,name=task_type,json=taskType,proto3,enum=worker.v1.TaskType" json:"task_type,omitempty"`
	// RandomForest hyperparameters
	NEstimators  int32  `protobuf:"varint,4,opt,name=n_estimators,json=nEstimators,proto3" json:"n_estimators,omitempty"`
	TargetColumn string `protobuf:"bytes,6,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	// Necessary for uncorrelated forests
	RandomSeed int32 `protobuf:"varint,7,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
	// NEW: Fields for deterministic dataset partitioning
	WorkerIndex  int32 `protobuf:"varint,8,opt,name=worker_index,json=workerIndex,proto3" json:"worker_index,omitempty"`
	TotalWorkers int32 `protobuf:"varint,9,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"`
	// Additional RandomForest hyperparameters (max_depth, max_features,
	// min_samples_split, min_samples_leaf, bootstrap, max_samples, criterion,
	// max_leaf_nodes, class_weight, oob_score), validated and converted to
	// strings by the master (internal/api) before being sent here. The
	// worker converts each value back to the right Python type generically
	// (see services/worker/worker_service.py) and forwards them as kwargs to
	// scikit-learn.
	Hyperparameters map[string]string `protobuf:"bytes,10,rep,name=hyperparameters,proto3" json:"hyperparameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TrainRequest) Reset() {
	*x = TrainRequest{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainRequest) ProtoMessage() {}

func (x *TrainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainRequest.ProtoReflect.Descriptor instead.
func (*TrainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{0}
}

func (x *TrainRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TrainRequest) GetDatasetUrl() string {
	if x != nil {
		return x.DatasetUrl
	}
	return ""
}

func (x *TrainRequest) GetTaskType() TaskType {
	if x != nil {
		return x.TaskType
	}
	return TaskType_UNSPECIFIED_TASK
}

func (x *TrainRequest) GetNEstimators() int32 {
	if x != nil {
		return x.NEstimators
	}
	return 0
}

func (x *TrainRequest) GetTargetColumn() string {
	if x != nil {
		return x.TargetColumn
	}
	return ""
}

func (x *TrainRequest) GetRandomSeed() int32 {
	if x != nil {
		return x.RandomSeed
	}
	return 0
}

func (x *TrainRequest) GetWorkerIndex() int32 {
	if x != nil {
		return x.WorkerIndex
	}
	return 0
}

func (x *TrainRequest) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

func (x *TrainRequest) GetHyperparameters() map[string]string {
	if x != nil {
		return x.Hyperparameters
	}
	return nil
}

type TrainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrainResponse) Reset() {
	*x = TrainResponse{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrainResponse) ProtoMessage() {}

func (x *TrainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrainResponse.ProtoReflect.Descriptor instead.
func (*TrainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{1}
}

func (x *TrainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TrainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PredictRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ModelId  string                 `protobuf:"bytes,1,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Features []float32              `protobuf:"fixed32,2,rep,packed,name=features,proto3" json:"features,omitempty"`
	// fields necessary to partition trained trees between the workers
	WorkerIndex   int32 `protobuf:"varint,3,opt,name=worker_index,json=workerIndex,proto3" json:"worker_index,omitempty"`    // Indice del worker (0, 1, 2...)
	TotalWorkers  int32 `protobuf:"varint,4,opt,name=total_workers,json=totalWorkers,proto3" json:"total_workers,omitempty"` // Totale worker attivi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictRequest) Reset() {
	*x = PredictRequest{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictRequest) ProtoMessage() {}

func (x *PredictRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictRequest.ProtoReflect.Descriptor instead.
func (*PredictRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{2}
}

func (x *PredictRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *PredictRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *PredictRequest) GetWorkerIndex() int32 {
	if x != nil {
		return x.WorkerIndex
	}
	return 0
}

func (x *PredictRequest) GetTotalWorkers() int32 {
	if x != nil {
		return x.TotalWorkers
	}
	return 0
}

type PredictResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Changed from single string to repeated to allow master-side global aggregation
	Predictions   []string `protobuf:"bytes,1,rep,name=predictions,proto3" json:"predictions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PredictResponse) Reset() {
	*x = PredictResponse{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PredictResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PredictResponse) ProtoMessage() {}

func (x *PredictResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PredictResponse.ProtoReflect.Descriptor instead.
func (*PredictResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{3}
}

func (x *PredictResponse) GetPredictions() []string {
	if x != nil {
		return x.Predictions
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{4}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_worker_v1_worker_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_worker_v1_worker_proto_rawDescGZIP(), []int{5}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_api_proto_worker_v1_worker_proto protoreflect.FileDescriptor

const file_api_proto_worker_v1_worker_proto_rawDesc = "" +
	"\n" +
	" api/proto/worker/v1/worker.proto\x12\tworker.v1\"\xcf\x03\n" +
	"\fTrainRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1f\n" +
	"\vdataset_url\x18\x02 \x01(\tR\n" +
	"datasetUrl\x120\n" +
	"\ttask_type\x18\x03 \x01(\x0e2\x13.worker.v1.TaskTypeR\btaskType\x12!\n" +
	"\fn_estimators\x18\x04 \x01(\x05R\vnEstimators\x12#\n" +
	"\rtarget_column\x18\x06 \x01(\tR\ftargetColumn\x12\x1f\n" +
	"\vrandom_seed\x18\a \x01(\x05R\n" +
	"randomSeed\x12!\n" +
	"\fworker_index\x18\b \x01(\x05R\vworkerIndex\x12#\n" +
	"\rtotal_workers\x18\t \x01(\x05R\ftotalWorkers\x12V\n" +
	"\x0fhyperparameters\x18\n" +
	" \x03(\v2,.worker.v1.TrainRequest.HyperparametersEntryR\x0fhyperparameters\x1aB\n" +
	"\x14HyperparametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\x05\x10\x06\"C\n" +
	"\rTrainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x0ePredictRequest\x12\x19\n" +
	"\bmodel_id\x18\x01 \x01(\tR\amodelId\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\x02R\bfeatures\x12!\n" +
	"\fworker_index\x18\x03 \x01(\x05R\vworkerIndex\x12#\n" +
	"\rtotal_workers\x18\x04 \x01(\x05R\ftotalWorkers\"3\n" +
	"\x0fPredictResponse\x12 \n" +
	"\vpredictions\x18\x01 \x03(\tR\vpredictions\"\x0f\n" +
	"\rHealthRequest\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy*N\n" +
	"\bTaskType\x12\x14\n" +
	"\x10UNSPECIFIED_TASK\x10\x00\x12\x17\n" +
	"\x13CLASSIFICATION_TASK\x10\x01\x12\x13\n" +
	"\x0fREGRESSION_TASK\x10\x022\xc5\x01\n" +
	"\x06Worker\x12:\n" +
	"\x05Train\x12\x17.worker.v1.TrainRequest\x1a\x18.worker.v1.TrainResponse\x12@\n" +
	"\aPredict\x12\x19.worker.v1.PredictRequest\x1a\x1a.worker.v1.PredictResponse\x12=\n" +
	"\x06Health\x12\x18.worker.v1.HealthRequest\x1a\x19.worker.v1.HealthResponseBLZJgithub.com/bytelisa/distributed-random-forest/api/proto/worker/v1;workerv1b\x06proto3"

var (
	file_api_proto_worker_v1_worker_proto_rawDescOnce sync.Once
	file_api_proto_worker_v1_worker_proto_rawDescData []byte
)

func file_api_proto_worker_v1_worker_proto_rawDescGZIP() []byte {
	file_api_proto_worker_v1_worker_proto_rawDescOnce.Do(func() {
		file_api_proto_worker_v1_worker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_worker_v1_worker_proto_rawDesc), len(file_api_proto_worker_v1_worker_proto_rawDesc)))
	})
	return file_api_proto_worker_v1_worker_proto_rawDescData
}

var file_api_proto_worker_v1_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_worker_v1_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_proto_worker_v1_worker_proto_goTypes = []any{
	(TaskType)(0),           // 0: worker.v1.TaskType
	(*TrainRequest)(nil),    // 1: worker.v1.TrainRequest
	(*TrainResponse)(nil),   // 2: worker.v1.TrainResponse
	(*PredictRequest)(nil),  // 3: worker.v1.PredictRequest
	(*PredictResponse)(nil), // 4: worker.v1.PredictResponse
	(*HealthRequest)(nil),   // 5: worker.v1.HealthRequest
	(*HealthResponse)(nil),  // 6: worker.v1.HealthResponse
	nil,                     // 7: worker.v1.TrainRequest.HyperparametersEntry
}
var file_api_proto_worker_v1_worker_proto_depIdxs = []int32{
	0, // 0: worker.v1.TrainRequest.task_type:type_name -> worker.v1.TaskType
	7, // 1: worker.v1.TrainRequest.hyperparameters:type_name -> worker.v1.TrainRequest.HyperparametersEntry
	1, // 2: worker.v1.Worker.Train:input_type -> worker.v1.TrainRequest
	3, // 3: worker.v1.Worker.Predict:input_type -> worker.v1.PredictRequest
	5, // 4: worker.v1.Worker.Health:input_type -> worker.v1.HealthRequest
	2, // 5: worker.v1.Worker.Train:output_type -> worker.v1.TrainResponse
	4, // 6: worker.v1.Worker.Predict:output_type -> worker.v1.PredictResponse
	6, // 7: worker.v1.Worker.Health:output_type -> worker.v1.HealthResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_worker_v1_worker_proto_init() }
func file_api_proto_worker_v1_worker_proto_init() {
	if File_api_proto_worker_v1_worker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_worker_v1_worker_proto_rawDesc), len(file_api_proto_worker_v1_worker_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_worker_v1_worker_proto_goTypes,
		DependencyIndexes: file_api_proto_worker_v1_worker_proto_depIdxs,
		EnumInfos:         file_api_proto_worker_v1_worker_proto_enumTypes,
		MessageInfos:      file_api_proto_worker_v1_worker_proto_msgTypes,
	}.Build()
	File_api_proto_worker_v1_worker_proto = out.File
	file_api_proto_worker_v1_worker_proto_goTypes = nil
	file_api_proto_worker_v1_worker_proto_depIdxs = nil
}
