# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api.proto.worker.v1 import worker_pb2 as api_dot_proto_dot_worker_dot_v1_dot_worker__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/proto/worker/v1/worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WorkerStub(object):
    """EXPORTED SERVICES

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Train = channel.unary_unary(
                '/worker.v1.Worker/Train',
                request_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainResponse.FromString,
                _registered_method=True)
        self.Predict = channel.unary_unary(
                '/worker.v1.Worker/Predict',
                request_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/worker.v1.Worker/Health',
                request_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
                response_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
                _registered_method=True)


class WorkerServicer(object):
    """EXPORTED SERVICES

    """

    def Train(self, request, context):
        """Start training a subset of trees
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Predict(self, request, context):
        """Inference on given input
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """Health check for fault tolerance
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Train': grpc.unary_unary_rpc_method_handler(
                    servicer.Train,
                    request_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainRequest.FromString,
                    response_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainResponse.SerializeToString,
            ),
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictRequest.FromString,
                    response_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.FromString,
                    response_serializer=api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'worker.v1.Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('worker.v1.Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Worker(object):
    """EXPORTED SERVICES

    """

    @staticmethod
    def Train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.v1.Worker/Train',
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainRequest.SerializeToString,
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.TrainResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.v1.Worker/Predict',
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictRequest.SerializeToString,
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.PredictResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/worker.v1.Worker/Health',
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthRequest.SerializeToString,
            api_dot_proto_dot_worker_dot_v1_dot_worker__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
