
# implements the interface WorkerService as per defined in .proto file


import time
from concurrent import futures
import grpc

# Import files generated by Protobuf
from api.proto.worker.v1 import worker_pb2
from api.proto.worker.v1 import worker_pb2_grpc

# todo fix all fake simulated things

class WorkerService(worker_pb2_grpc.WorkerServiceServicer):

    def Train(self, request, context):

        print(f"[Worker] Received training request for model {request.model_id}.")
        print(f"        Dataset: {request.dataset_url}")
        print(f"        Trees: {request.n_estimators}")
        print(f"        Task: {worker_pb2.TaskType.Name(request.task_type)}")

        # fake training
        time.sleep(2)

        return worker_pb2.TrainResponse(
            success=True,
            message="Training completed. (fake)",
        )


    def Predict(self, request, context):

        print(f"[Worker] Received prediction request for model {request.model_id}.")

        #fake prediction
        return worker_pb2.PredictResponse(value=0.0)


    def Health(self, request, context):

        # Helath check: master wants to know if worker is active
        print("[Worker] Health check received.")
        return worker_pb2.HealthResponse(healthy=True)


