import os
# implements the interface of the Worker Service as per defined in .proto file


import time
from concurrent import futures
import grpc

# Import files generated by Protobuf
from api.proto.worker.v1 import worker_pb2
from api.proto.worker.v1 import worker_pb2_grpc
from services.worker.ml import model

# Note: all functions take and return objects defined in the two generated _pb2.py files,
# which implement the interface worker.proto in python.


class WorkerService(worker_pb2_grpc.WorkerServicer):

    def _convert_type(self, request):
        if request.task_type == worker_pb2.TaskType.CLASSIFICATION_TASK:
            return "classifier"
        elif request.task_type == worker_pb2.TaskType.REGRESSION_TASK:
            return "regressor"


    def Train(self, request, context):

        print(f"[Worker] Received training request for model {request.model_id}.")
        print(f"         Dataset: {request.dataset_url}")
        print(f"         Trees: {request.n_estimators}")
        print(f"         Task: {worker_pb2.TaskType.Name(request.task_type)}")

        # time.sleep(2)

        dataframe = model.load_dataset(request.dataset_url)
        trained_model = model.train_model(
            data=dataframe,
            target_column=request.target_column,
            model_type=self._convert_type(request),
            n_estimators=request.n_estimators
        )

        if trained_model is None:
            print(f"[Worker] Training failed for model {request.model_id}.")
            return worker_pb2.TrainResponse(
                success=False,
                message=f"Training failed for model {request.model_id}."
            )

        model.save_model(trained_model, f"models/model_{request.model_id}.joblib")


        return worker_pb2.TrainResponse(
            success=True,
            message="Training completed.",
        )


    def Predict(self, request, context):
        print(f"[Worker] Received Prediction request for model {request.model_id}")

        # Find path
        filename = f"model_{request.model_id}.joblib"
        model_path = os.path.join("models/", filename)

        try:
            # Send raw feature list to model
            result = model.load_and_predict(
                model_path=model_path,
                features=list(request.features)
            )

            return worker_pb2.PredictResponse(prediction=result)

        except FileNotFoundError:
            context.set_code(grpc.StatusCode.NOT_FOUND)
            context.set_details("[Worker] Model not found.")
            return worker_pb2.PredictResponse()
        except Exception as e:
            print(f"[Error Predict] {e}")
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(str(e))
            return worker_pb2.PredictResponse()

    def Health(self, request, context):

        # Health check: master wants to know if worker is active
        print("[Worker] Health check received.")
        return worker_pb2.HealthResponse(healthy=True)



